export const PROJECTS = [
  {
    id: 'proj-1',
    number: '01',
    name: 'Gamified Habit Tracker',
    description: 'An RPG-style habit tracker where completing daily quests levels up your character across five attributes, unlocks achievement badges, and climbs a global leaderboard — with GitHub-style check-in calendars to visualize streaks.',
    stack: ['React', 'Vite', 'Tailwind', 'Django', 'Django REST Framework'],
    image: '/projects/gamified-habit-tracker.png',
    github: 'https://github.com/bryanfernandez-eng/gamified-habit-tracker',
    live: null,
  },
  {
    id: 'proj-2',
    number: '02',
    name: 'Cashcore',
    description: 'A fintech app that helps college students take control of their money — track budgets and spending, manage stock portfolios, and monitor loans and savings, with bank data connected through the Plaid API.',
    stack: ['React Native', 'Expo', 'TypeScript', 'Django', 'PostgreSQL'],
    image: '/projects/cashcore.png',
    github: 'https://github.com/Ceaseless04/Cashcore',
    live: null,
  },
  {
    id: 'proj-3',
    number: '03',
    name: 'GatherU',
    description: 'An event discovery platform for FIU students — browse and RSVP to club events, follow clubs, comment, and get recommendations ranked by your interests. Built with the INIT BUILD WebDev Advanced cohort.',
    stack: ['React', 'Tailwind', 'Django', 'PostgreSQL', 'AWS S3'],
    image: '/projects/gather-u.png',
    github: 'https://github.com/hpitta26/club-event-hub',
    live: null,
  },
  {
    id: 'proj-4',
    number: '04',
    name: 'Translate Flow',
    description: 'A multi-agent AI translation system that localizes entire websites in minutes. Agents work through a 4-stage pipeline — content detection, parallel translation, quality review, and refinement — to deliver context-aware translations across 15+ languages. Built at ShellHacks 2025.',
    stack: ['Google Cloud ADK', 'Gemini 2.0', 'FastAPI', 'Python'],
    image: '/projects/translate-flow.png',
    github: 'https://github.com/hpitta26/Shellhacks-2025',
    live: null,
  },
  {
    id: 'proj-5',
    number: '05',
    name: 'Roadmap AI',
    description: 'An AI assistant that turns project ideas into detailed, actionable roadmaps — step-by-step plans tailored to your goals, tech stack, and timeline, with smart task management and a project-aware AI chat for guidance and code reviews.',
    stack: ['Google ADK', 'Gemini 2.0', 'FastAPI', 'React', 'PostgreSQL'],
    image: '/projects/roadmap-ai.png',
    github: null,
    live: null,
  },
  {
    id: 'proj-6',
    number: '06',
    name: 'Moviq',
    description: 'A movie discovery and tracking app built around personalized discovery — browse movies and TV shows, rate films, build and share playlists, and generate an AI-backed taste profile that learns what you actually like.',
    stack: ['React', 'Vite', 'FastAPI', 'SQLAlchemy', 'OpenAI'],
    image: '/projects/moviq.png',
    github: null,
    live: null,
  },
  {
    id: 'proj-7',
    number: '07',
    name: 'CareerPilot',
    description: 'An AI-powered job search copilot that streamlines the application process — track applications, generate tailored resumes and cover letters, and get AI-driven insights to land your next role faster.',
    stack: ['React', 'FastAPI', 'PostgreSQL', 'OpenAI'],
    image: '/projects/career-pilot.png',
    github: 'https://github.com/bryanfernandez-eng/CareerPilot',
    live: null,
  },
  {
    id: 'proj-8',
    number: '08',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Java', 'Spring Boot'],
    image: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='500'%3E%3Crect width='800' height='500' fill='%231a1a2e'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='monospace' font-size='72' fill='%2339d353'%3E08%3C/text%3E%3C/svg%3E",
    github: '#',
    live: null,
  },
  {
    id: 'proj-9',
    number: '09',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['React Native', 'Expo'],
    image: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='500'%3E%3Crect width='800' height='500' fill='%231a1a2e'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='monospace' font-size='72' fill='%2339d353'%3E09%3C/text%3E%3C/svg%3E",
    github: '#',
    live: null,
  },
  {
    id: 'proj-10',
    number: '10',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Rust', 'WebAssembly'],
    image: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='500'%3E%3Crect width='800' height='500' fill='%231a1a2e'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='monospace' font-size='72' fill='%2339d353'%3E10%3C/text%3E%3C/svg%3E",
    github: '#',
    live: null,
  },
]
