export const PROJECTS = [
  {
    id: 'proj-1',
    number: '01',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['React', 'Node.js'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=01',
    github: '#',
    live: null,
  },
  {
    id: 'proj-2',
    number: '02',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Python', 'FastAPI'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=02',
    github: '#',
    live: null,
  },
  {
    id: 'proj-3',
    number: '03',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['TypeScript', 'PostgreSQL'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=03',
    github: '#',
    live: null,
  },
  {
    id: 'proj-4',
    number: '04',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Go', 'Docker'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=04',
    github: '#',
    live: null,
  },
  {
    id: 'proj-5',
    number: '05',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['React', 'Flask'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=05',
    github: '#',
    live: null,
  },
  {
    id: 'proj-6',
    number: '06',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Next.js', 'Tailwind'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=06',
    github: '#',
    live: null,
  },
  {
    id: 'proj-7',
    number: '07',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Django', 'Redis'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=07',
    github: '#',
    live: null,
  },
  {
    id: 'proj-8',
    number: '08',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Java', 'Spring Boot'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=08',
    github: '#',
    live: null,
  },
  {
    id: 'proj-9',
    number: '09',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['React Native', 'Expo'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=09',
    github: '#',
    live: null,
  },
  {
    id: 'proj-10',
    number: '10',
    name: 'Coming Soon',
    description: 'This project is on its way. Check back soon for updates.',
    stack: ['Rust', 'WebAssembly'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=10',
    github: '#',
    live: null,
  },
]
