export const PROJECTS = [
  {
    id: 'proj-1',
    number: '01',
    name: 'Project Alpha',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    stack: ['React', 'Node.js', 'PostgreSQL', 'WebSockets'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=alpha',
    github: '#',
    live: '#',
  },
  {
    id: 'proj-2',
    number: '02',
    name: 'Project Beta',
    description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute.',
    stack: ['Next.js', 'Prisma', 'Tailwind', 'Resend'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=beta',
    github: '#',
    live: null,
  },
  {
    id: 'proj-3',
    number: '03',
    name: 'Project Gamma',
    description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint.',
    stack: ['Python', 'FastAPI', 'Redis', 'Docker'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=gamma',
    github: '#',
    live: null,
  },
  {
    id: 'proj-4',
    number: '04',
    name: 'Project Delta',
    description: 'Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum.',
    stack: ['Go', 'gRPC', 'Kubernetes', 'GitHub Actions'],
    image: 'https://placehold.co/800x500/1a1a2e/39d353?text=delta',
    github: '#',
    live: '#',
  },
]
